### ISSUE TITLE
输出代码不完善

### ISSUE THREAD

**Issue by newyorkthink** [LiangYang666/ChatGPT-Web#10]
![image](https://user-images.githubusercontent.com/87791643/226273823-7159e669-e804-41c5-84f0-e8ed59c3186b.png)
这代码 格式不行

**Comment by LiangYang666** [comment]
> ![image](https://user-images.githubusercontent.com/87791643/226273823-7159e669-e804-41c5-84f0-e8ed59c3186b.png) 这代码 格式不行

这应该是api输出的结果不完整，比如markdown代码段的三引号可能只有前面三个输出了，后面三个不完整，重新提问输出完整应该就正常了

**Comment by LiangYang666** [comment]
![image](https://user-images.githubusercontent.com/38237931/226276313-a3d78d73-f747-49ad-b78a-2000bb29bb76.png)
