### ISSUE TITLE
web页面窗口大小设置

### ISSUE THREAD

**Issue by MrHJPeng** [LiangYang666/ChatGPT-Web#19]
首先感谢作者共享此项目，在非docker环境是最方便的部署方式了
另外请教下
1. 如何设置web页面窗口大小呢，默认100%的话还有很多空白的地方，但是浏览器放大的话字体又很大不舒服，哪里能改这个大小呢？
2. 如何禁用此功能呢？“支持实时流获取，即逐字获取动态加载显示”

谢谢

**Comment by LiangYang666** [comment]
你好，
关于1，可进入`templates/index.html`中将`.all-container`样式`max-height:100%`，以及`.right-container`样式`width: 80%;`就可以调整大小了，这两处分别在24行和73行处

关于2:
修改`main.py`文件33行处，`STREAM_FLAG = False`

以上行数都针对当前版本代码

**Comment by MrHJPeng** [comment]
> 你好， 关于1，可进入`templates/index.html`中将`.all-container`样式`max-height:100%`，以及`.right-container`样式`width: 80%;`就可以调整大小了，这两处分别在24行和73行处
> 
> 关于2: 修改`main.py`文件33行处，`STREAM_FLAG = False`
> 
> 以上行数都针对当前版本代码

感谢感谢！
