### ISSUE TITLE
为什么我在发消息都时候出错了

### ISSUE THREAD

**Issue by 110wuqu** [LiangYang666/ChatGPT-Web#3]
![image](https://user-images.githubusercontent.com/49581935/224463543-2edf2e8e-f610-4553-a622-9cd409d2be1d.png)

**Comment by 110wuqu** [comment]
![Uploading image.png…]()

**Comment by LiangYang666** [comment]
> ![image](https://user-images.githubusercontent.com/49581935/224463543-2edf2e8e-f610-4553-a622-9cd409d2be1d.png)

一般是你的代理有问题

**Comment by LiangYang666** [comment]
建议使用美国、日本、新加坡、德国、韩国等地的代理，大陆及港澳台无法使用
