### ISSUE TITLE
关于message_history的存储

### ISSUE THREAD

**Issue by nobody1121** [LiangYang666/ChatGPT-Web#30]
通过railway部署项目，每次重新部署会导致之前的聊天记录消失，想问下有办法做聊天记录的备份迁移吗

**Comment by LiangYang666** [comment]
这一块没做，后面可以考虑加一个下载按钮来下载聊天记录，然后二次部署时用户可以上传聊天记录，目前在用nodejs写后端做vercel的部署，做完后进行开发

**Comment by nobody1121** [comment]
好的，辛苦了大佬

**Comment by LiangYang666** [comment]
已经更新了可以下载以及上传合并聊天记录，vercel部署放弃了，更新了Zeabur部署教程，这个比railway更好一些，没有时间限制，而且可以自定义域名的主机名，推荐使用

**Comment by nobody1121** [comment]
感谢大佬
