### ISSUE TITLE
部署到了Zeabur上 ，但还是有部分cdnjs.cloudflare.com的资源需要代理

### ISSUE THREAD

**Issue by PAACY** [LiangYang666/ChatGPT-Web#42]
我把项目部署到了Zeabur上 ，但还是有部分cdnjs.cloudflare.com的资源，比如https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js这种需要代理才能获取到

**Comment by PAACY** [comment]
请问这种情况该怎么办啊

**Comment by LiangYang666** [comment]
这样吗，我还没出现过获取不到这个诶，你直接打开链接下载不了这个文件吗，在新的浏览器上我不代理也能下载这个文件啊
https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js

PAACY ***@***.***> 于 2023年8月15日周二 下午9:09写道：

**Comment by PAACY** [comment]
嗯是的，我直接打开链接下载不了这个文件，必须要开代理才可以。。。不知道啥情况

**Comment by PAACY** [comment]
嗯，我这没禁用缓存的话一开始开个代理获取到相关js后就可以，但是禁用了缓存就必须要代理了。。。为什么我这就要代理啊。。。

**Comment by LiangYang666** [comment]
可能各地运营商限制的不一样可能，后面考虑下换成国内的镜像

PAACY ***@***.***> 于 2023年8月15日周二 下午9:43写道：

**Comment by PAACY** [comment]
哦哦原来这个还有国内镜像的呀，明白了明白了，我刚刚找到了一个这个：js.cdn.wenlei.club，真的很感谢呀
