### ISSUE TITLE
无法切换成其他模型比如 gpt-4

### ISSUE THREAD

**Issue by javamore** [LiangYang666/ChatGPT-Web#44]
你好LiangYang，
首先非常感谢你的这个作品，部署简易且很好用，谢谢！

我最近碰到了一个问题，我想试着把你默认用的gpt-3-turbo切换成gpt-4的模型，但是我试着在代码里直接改发现没有效果，他还是会显示用的是gpt-3-turbo。

我测试我用的模型的方法：
因为我现在的账号的rate limit是每分钟只能发3条消息，我通过超过这个限制让openai返回一个报错信息，里面会显示我正在使用的模型，也就是gpt-3.5-turbo。

想问下切换模型该如何操作呢？谢谢！

**Comment by javamore** [comment]
已经确认我的api key可以调用gpt-4的模型的。

**Comment by LiangYang666** [comment]
hi，我没有gpt-4的api，因此未适配4.0的模型，可以尝试下修改图中第一个文件
![image](https://github.com/LiangYang666/ChatGPT-Web/assets/38237931/d0417cc4-ea16-47e6-a788-29e8938780cf)
如果请求体有特殊要求，可再修改下图中的请求参数
![image](https://github.com/LiangYang666/ChatGPT-Web/assets/38237931/512786e6-e270-4dc0-b240-134491d9296e)

**Comment by javamore** [comment]
Hi Leo,

我改了这些配置，现在可以成功调用gpt-4的模型了，感谢！

**Comment by mokioy** [comment]
求助，我是想换模型成deepseek。更改了上述提到文件中的模型，以及js中的提到gpt的地方，还是不行。报错如下：{"error":{"message":"Model Not Exist","type":"invalid_request_error","param":null,"code":"invalid_request_error"}}

**Comment by LiangYang666** [comment]
> 求助，我是想换模型成deepseek。更改了上述提到文件中的模型，以及js中的提到gpt的地方，还是不行。报错如下：{"error":{"message":"Model Not Exist","type":"invalid_request_error","param":null,"code":"invalid_request_error"}}

这个应该是api返回的结果，更换了api的地址吗，检查下api的endpoint，可以用阿里云百炼api接入，有免费token
