### ISSUE TITLE
我怎么能跳过代理？

### ISSUE THREAD

**Issue by Anyueit** [LiangYang666/ChatGPT-Web#5]
我不需要代理上网，如何跳过代理？屏蔽了flask_main.py里的两行代理没用

**Comment by Anyueit** [comment]
注释无效，最后引号内删除就好了。目前可以使用，感谢大佬，另外问下，我看引擎用的是3.5，问的当前日期是2021.10.28，是3.5的训练数据只到这个日期吗？

**Comment by Anyueit** [comment]
官网查到了，感谢

**Comment by LiangYang666** [comment]
> 注释无效，最后引号内删除就好了。目前可以使用，感谢大佬，另外问下，我看引擎用的是3.5，问的当前日期是2021.10.28，是3.5的训练数据只到这个日期吗？

好的，这说明应该是你系统的环境变量就有这两个变量，删除引号内容是覆盖了系统已有变量
