### ISSUE TITLE
没回我任何消息

### ISSUE THREAD

**Issue by newyorkthink** [LiangYang666/ChatGPT-Web#7]
![image](https://user-images.githubusercontent.com/87791643/225332973-2970f5e4-9f98-4a22-b276-f1cb4a1f0a22.png)

**Comment by LiangYang666** [comment]
> ![image](https://user-images.githubusercontent.com/87791643/225332973-2970f5e4-9f98-4a22-b276-f1cb4a1f0a22.png)
> 

请看看程序，上一个issue已让你麻烦给出程序报错信息了

**Comment by newyorkthink** [comment]
把你QQ发过来，QQ沟通，或者创建一个QQ群
